- name: configure catalogue component 
  hosts: catalogue
  become: yes
  tasks: 
  - name: disable default nodejs
    ansible.builtin.command: dnf module disable nodejs

  - name: enable nodejs:20
    ansible.builtin.command: dnf module enable nodejs:20 -yaml

  - name: install nodejs
    ansible.builtin.dnf:
      name: nodejs
      state: present

  - name: create roboshop system user
    ansible.builtin.user:
       name: roboshop
       shell: /sbin/nologin
       system: true
       home: /app

  - name: create app directory
    ansible.builtin.file:
      path: /app
      state: directory

  - name: download cart nodejs
    ansible.builtin.get_url:
        url: https://roboshop-artifacts.s3.amazonaws.com/catalogue-v3.zip 
        dest: /tmp/catalogue.zip                  
    
  # this module thinks file exists on ansible control server needs to extract on to remote machine
  # remote_src yes means file already exists on catalogue service

  - name: extract catalogue code 
    ansible.builtin.unarchive:
      src: /tmp/catalogue.zip
      dest: /app
      remote_src: yes

  - name: install dependencies
    community.general.npm:
      path: /app

  - name: copy catalogue service to system service
    ansible.builtin.copy:
      src: catalogue.service
      dest: /etc/systemd/system/catalogue.service

  - name: daemon reload
    ansible.builtin.systemd_reload:
      daemon_reload: true

  - name: start and enable catalogue
    ansible.builtin.service:
       name: catalogue
       state: started
       enabled: yes

  - name: copy mongo repo
    ansible.builtin.copy:
       src: mongo.repo
       dest: /etc/yum.repos.d/mongo.repo

  - name: install mongodb client
    ansible.builtin.dnf:
       name: mongodb-mongosh
       state: present

  - name: check products loaded or not 
    ansible.builtin.command: mongosh --host mongodb.daws84s.site --eval 'db.getMongo().getDBNames().indexOf("catalogue")'
    register: catalogue_output

  - name: print catalogue_output
    ansible.builtin.debug:
      msg: "{{ catalogue_output }}"

  - name: load products
    ansible.builtin.shell: mongosh --host mongodb.subbuaws.site </app/db/master-data.js
    when: catalogue_output / int < 0   