- name: configure catalogue service
  hosts: catalogue
  become: yes
  tasks: 
  - name: disable default nodejs
    ansible.builtin.command: dnf module disable nodejs

  - name: enable nodejs:20
    ansible.builtin.command: dnf module enable nodejs:20 -yaml

  - name: install nodejs
    ansible.builtin.dnf:
      name: nodejs
      state: present

  - name: create roboshop systemuser
    ansible.builtin.user:
      name: roboshop
      shell: /sbin/nologin
      system: true
      home: /app

  - name: create app directory
    ansible.builtin.file:
      path: /app
      state: directory

  - name: download cart node
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/catalogue-v3.zip
      dest: /tmp/catalogue.zip

  # this module thinks file exists on needs to extract on to remote machine
  # remote_src yes means file already exists in catalogue server

  - name: extract catalogue command_result
    ansible.builtin.unarchive:
      src: /tmp/catalogue/
      dest: /app
      remote_src: yes

  - name: install dependencies
    community.general.npm:
      path: /app

  - name: copy catalogue service to system directory
    ansible.builtin.copy:
      src: catalogue.service
      dest: /etc/systemd/system/catalogue.service      

  - name: systemctl daemon reload
    ansible.builtin.systemd_service:
     daemon_reload: true

  - name: start and enable catalogue
    ansible.builtin.service:
      name: catalogue
      state: started
      enabled: yes

  - name: copy mongod repo
    ansible.builtin.copy:
       src: mongo.repo
       dest: /etc/yum.repos.d/mongo.repo

  - name: install mongodb client
    ansible.builtin.dnf:
       name: mondodb-mongosh
       state: present

  - name: check products loaded or not 
    ansible.builtin.command: mongosh --host mongodb.subbuaws.site --eval 'db.getMongo(). getDBNames().index of ("catalogue")'
    register: catalogue_output

  - name: print catalogue output
    ansible.builtin.debug:
     msg: "{{ catalogue_output }}"

  - name: load products
    ansible.builtin.shell: mongosh --host mongodb.subbuaws.site </app/db/master-data.js
    when: catalogue_output.stdout / int < 0   