- name: configure frontend component 
  hosts: frontend 
  become: yes 
  tasks: 
  - name: disable deafult nginx 
    ansible.builtin.command: 

  - name: enable nginx:1.24 
    ansible.builtin.command: 

  - name: install nginx 
    ansible.builtin.dnf: 
       name: nginx 
       state: installed 

  - name: start and enable nginx 
    ansible.builtin.service: 
       name: nginx 
       state: started 
       enabled: yes 

  - name: remove html directory 
    ansible.builtin.file: 
       path: /usr/share/nginx/html
       state: absent 

  - name: create html directory 
    ansible.builtin.file: 
       path: /usr/share/nginx/html 
       state: directory 

  - name: download frontend code 
    ansible.builtin.url: 
       url:  https://roboshop-artifacts.s3.amazonaws.com/frontend-v3.zip
       dest: /tmp/frontend.zip 

  - name: extract the frontend code 
    ansible.builtin.unarchive: 
       src: /tmp/frontend.zip 
       dest: /app 
       remote_src: yes 

  - name: remove default nginx conf 
    ansible.builtin.file: 
       path: /etc/nginx/nginx.conf 
       state: absent 

  - name: copy roboshop nginx conf 
    ansible.builtin.file: 
       path: /etc/nginx/nginx.conf 
       state: directory 

  - name: restart nginx 
    amsible.builtin.service: 
       name: nginx 
       state: restarted                                               