- name: configure frontend component
  hosts: frontend
  become: yes
  tasks:
  - name: disable default nginx
    ansible.builtin.command: dnf module disable nginx 

  - name: enable nginx:1.24
    ansible.builtin.command: dnf module enable nginx:1.24 -y 

  - name: install nginx -y  
    ansible.builtin.dnf: 
      name: nginx
      state: present

  - name: start and enable nginx
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes

  - name: remove default html
    ansible.builtin.file:
      path: /usr/share/nginx/html
      state: absent

  - name: create html directory
    ansible.builtin.file:
      path: /usr/share/nginx/html
      state: directory       

  - name: download frontend code
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/frontend-v3.zip
      dest: /tmp/frontend.zip

  - name: unzip frontend.zip
    ansible.builtin.unarchive:
      src: /tmp/frontend.zip
      dest: /usr/share/nginx/html
      remote_src: yes

  - name: remove default nginx.conf
    ansible.builtin.file:
      path: /etc/nginx/nginx.conf
      dest: absent

  - name: copy roboshop nginx.conf 
    ansible.builtin.copy:
      src: nginx.conf
      dest: /ect/nginx/nginx.conf 

  - name: restart nginx
    ansible.builtin.service:
      name: nginx
      state: restarted           