- name: configuring mongodb server 
  hosts: mongodb 
  become: yes 
  tasks: 
  - name: copying mongodb repo 
    ansible.builtin.copy: 
       src: mongo.repo 
       dest: /etc/yum.repos.d/mongo.repo 

  - name: install mongodb-server 
    ansible.builtin.dnf: 
       name: mongodb-server 
       state: installed 

  - name: start the mongodb-server 
    ansible.builtin.service: 
       name: mongod 
       state: started 
       enabled: yes 

  - name: allowing connections from mongodb-server 
    ansible.builtin.replace: 
       path: /etc/mongod.conf 
       regexp: '127.0.0.0'
       replace: '0.0.0.0' 

  - name: restart mongodb server 
    ansible.builtin.service: 
        name: mongod 
        state: restarted                                  