- name: configure user component
  hosts: user
  become: yes
  tasks:
  - name: disable nodejs
    ansible.builtin.command: dnf module disable nodejs -y 

  - name: enable nodejs:20
    ansible.builtin.command: dnf module enable nodejs:20 -y 

  - name: install nodejs
    ansible.builtin.dnf: 
      name: nodejs
      state: installed

  - name: creating system user roboshop
    ansible.builtin.user: 
      user: roboshop
      shell: /sbin/nologin
      home: /app

  - name: creating app directory
    ansible.builtin.file:
      path: /app
      state: directory

  - name: Downloading user code
    ansible.builtin.get_url:
      url: 
      dest: /tmp/user.zip

  - name: extract user code
    ansible.builtin.unarchive:
      src: /tmp/user.zip
      dest: /app
      remote_src: yes

  - name: install dependencies
    ansible.builtin.npm:
      path: /app

  - name: copy user service
    ansible.builtin.copy:
      src: user.service
      dest: /etc/systemd/system/user.service

  - name: daemon reload
    ansible.builtin.systemd_service:
      daemon_reload: yes

  - name: start and enable user
    ansible.builtin.service:
      name: user
      state: started
      enabled: yes
          
