- name: configuring user component 
  hosts: user 
  become: yes 
  tasks:  
  - name: disbale user 
    ansible.builtin.command: dnf module disable user -y 

  - name: enable user 
    ansible.builtin.command: dnf module enable user -y 

  - name: install user 
    ansible.builtin.dnf: 
        name: user 
        state: started 

  - name: creating system user 
    ansible.builtin.user: 
       name: roboshop  
       shell: /sbin/shell 
       system: true 
       home: /app 

  - name: creating /app directory 
    ansible.builtin.file: 
        path: /app 
        state: directory 

  - name: download catalogue 
    ansible.builtin.url: 
      url: curl -L -o /tmp/user.zip https://roboshop-artifacts.s3.amazonaws.com/user-v3.zip 
      dest: /tmp/user.zip 
      remote_src: true 

  - name: extract user code 
    ansible.builtin.archive: 
       src: /tmp/user.zip 
       dest: /app 

  - name: install dependencies  
    general.community.npm: 
       path: /app 

  - name: creating systemctl service  
    ansible.builtin.copy: 
        src: user.service 
        dest: /etc/yum.repos.d/user.service 

  - name: creating systemctl service 
    ansible.builtin.systemd_service: 
       daemon_reload: true  

  - name: start and enable 
    ansible.builtin.service: 
        name: user 
        state: started 
        enabled: yes                                        